# Profil PROD - MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tp1db
spring.datasource.username=root
spring.datasource.password=mysqlpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}